version: '3'
services:
  streamlit-massql-post-mn:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit-massql-post-mn
    volumes:
      - ./logs:/app/logs:rw
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: massqlpostmn.wanglab.science
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: massqlpostmn.wanglab.science
      LETSENCRYPT_EMAIL: mwang87@gmail.com

networks:
  nginx-net:
    external:
      name: nginx-net